### ISSUE TITLE
Markdown rendered differently in documentation than in Readme

### ISSUE THREAD

**Issue by andreasKroepelin** [compintell/Mooncake.jl#464]
#463 moved content from the Readme to the documentstions but the Markdown rendering is slightly different, apparently.
Here is what I've found:
1. Strikethrough formatting (`~~like this~~`) is displayed verbatim in the docs.
2. Headings are lowercased for heading-links in the Readme but not in the docs. This leads to dead links.

Both happens (at least) in the [performance section](https://compintell.github.io/Mooncake.jl/dev/#Performance).

**Comment by willtebbutt** [comment]
Oops! I'll get this fixed.

**Comment by willtebbutt** [comment]
This should now be fixed. (I accidentally just pushed directly to main 🤦 . I've just changed the branch protection rules to prevent me from accidentally doing that in the future...).

**Comment by andreasKroepelin** [comment]
I think the second point is not fixed, some internal links still don't work, for example the link to the Project status section in the Performance section.

I edited the issue shortly after creating it, maybe you've only seen the original version.

**Comment by willtebbutt** [comment]
Ah, sorry, yes. Good point. I'll take another look.

**Comment by willtebbutt** [comment]
I believe this is now _actually_ resolved. Please feel free to reopen if it turns out it's not!

**Comment by andreasKroepelin** [comment]
Looks good now 👍🏼
